[client]
showErrorDetails = false

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
maxUploadSize = 100

[theme]
primaryColor = "#4f46e5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f4f6"
textColor = "#1f2937"
font = "sans serif"
